YAML: 1.0
bag_path: /home/fan/ssd/Projects/ros2_ws/data/bags/NCLT/ros2_0110
lio_yaml: /home/fan/ssd/Projects/ros2_ws/src/offline_mapping/config/velodyne_nclt.yaml
map_data: ./data/ch9/map_data/
kf_path: /home/fan/ssd/Projects/ros2_ws/src/offline_mapping/data/output/keyframes/
origin:
  - 276726.56265798624
  - 4685961.4821172003
  - 272.80900000000003
common:
  dataset: nclt
  lid_topic: points_raw
  imu_topic: imu_raw
  gnss_topic: gps_rtk_fix
gnss_ext:
  t: [0, 0.24, -0.283]
gnss_outlier_th: 1.0
gnss_pos_noise: 2.0
gnss_height_noise_ratio: 10.0
gnss_ang_noise: 5.0
lidar_continuous_num: 5
max_iterations: 100